//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWonder_Desktop.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWonder_Desktop.language.LocalResources", typeof(LocalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string label_About {
            get {
                return ResourceManager.GetString("label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there i am using .
        /// </summary>
        public static string label_About_me {
            get {
                return ResourceManager.GetString("label_About_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string label_Accept {
            get {
                return ResourceManager.GetString("label_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you using the messenger on your mobile ?.
        /// </summary>
        public static string label_Are_you_using {
            get {
                return ResourceManager.GetString("label_Are_you_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach File.
        /// </summary>
        public static string label_Attach_File {
            get {
                return ResourceManager.GetString("label_Attach_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string label_Background {
            get {
                return ResourceManager.GetString("label_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block User.
        /// </summary>
        public static string label_Block_User_ListBoxItem {
            get {
                return ResourceManager.GetString("label_Block_User_ListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blocked contacts will no longer be able to call you or send you messages..
        /// </summary>
        public static string label_blocked {
            get {
                return ResourceManager.GetString("label_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string label_BoxItem_female {
            get {
                return ResourceManager.GetString("label_BoxItem_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string label_Btn_Block {
            get {
                return ResourceManager.GetString("label_Btn_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block User.
        /// </summary>
        public static string label_Btn_Block_User {
            get {
                return ResourceManager.GetString("label_Btn_Block_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string label_Btn_cancel {
            get {
                return ResourceManager.GetString("label_Btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string label_Btn_CloseProfile {
            get {
                return ResourceManager.GetString("label_Btn_CloseProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string label_btn_delete {
            get {
                return ResourceManager.GetString("label_btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete call.
        /// </summary>
        public static string label_Btn_delete_call {
            get {
                return ResourceManager.GetString("label_Btn_delete_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Chat.
        /// </summary>
        public static string label_Btn_delete_chat {
            get {
                return ResourceManager.GetString("label_Btn_delete_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string label_Btn_EditProfile {
            get {
                return ResourceManager.GetString("label_Btn_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET PROFILE PHOTO.
        /// </summary>
        public static string label_Btn_EditProfileImage {
            get {
                return ResourceManager.GetString("label_Btn_EditProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string label_Btn_Forgot {
            get {
                return ResourceManager.GetString("label_Btn_Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string label_Btn_Login {
            get {
                return ResourceManager.GetString("label_Btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Here? Create New Acount.
        /// </summary>
        public static string label_Btn_newAcount {
            get {
                return ResourceManager.GetString("label_Btn_newAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string label_Btn_Open_img {
            get {
                return ResourceManager.GetString("label_Btn_Open_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string label_Btn_Pause {
            get {
                return ResourceManager.GetString("label_Btn_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string label_Btn_Play {
            get {
                return ResourceManager.GetString("label_Btn_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string label_Btn_save_EditProfile {
            get {
                return ResourceManager.GetString("label_Btn_save_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string label_Btn_Save_img {
            get {
                return ResourceManager.GetString("label_Btn_Save_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string label_btnRpeat {
            get {
                return ResourceManager.GetString("label_btnRpeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call your friends and have a nice audio conversation..
        /// </summary>
        public static string label_Call_your_friends {
            get {
                return ResourceManager.GetString("label_Call_your_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling.
        /// </summary>
        public static string label_Calling {
            get {
                return ResourceManager.GetString("label_Calling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language :.
        /// </summary>
        public static string label_Change_language {
            get {
                return ResourceManager.GetString("label_Change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Color.
        /// </summary>
        public static string label_ChangeColorButton {
            get {
                return ResourceManager.GetString("label_ChangeColorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed his chat color.
        /// </summary>
        public static string label_Changed_his_chat_color {
            get {
                return ResourceManager.GetString("label_Changed_his_chat_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop notifications.
        /// </summary>
        public static string label_Chk_Desktop_Notifications {
            get {
                return ResourceManager.GetString("label_Chk_Desktop_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sound notifications.
        /// </summary>
        public static string label_Chk_Enable_Sound_notifications {
            get {
                return ResourceManager.GetString("label_Chk_Enable_Sound_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound.
        /// </summary>
        public static string label_Chk_Play_sound {
            get {
                return ResourceManager.GetString("label_Chk_Play_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive notifications for new messages.
        /// </summary>
        public static string label_Chk_Receive_notifications {
            get {
                return ResourceManager.GetString("label_Chk_Receive_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your own stickers from our new stickers pack.
        /// </summary>
        public static string label_Choose_your_stickers {
            get {
                return ResourceManager.GetString("label_Choose_your_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string label_closeButton {
            get {
                return ResourceManager.GetString("label_closeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string label_closeSetting_StickersButton {
            get {
                return ResourceManager.GetString("label_closeSetting_StickersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection type :.
        /// </summary>
        public static string label_connation_type {
            get {
                return ResourceManager.GetString("label_connation_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your webcam and get started!.
        /// </summary>
        public static string label_Connect_your_webcam {
            get {
                return ResourceManager.GetString("label_Connect_your_webcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It may take few minutes it depends on your connection.
        /// </summary>
        public static string label_connection {
            get {
                return ResourceManager.GetString("label_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control your Notifications With..
        /// </summary>
        public static string label_Control_your_Notifications {
            get {
                return ResourceManager.GetString("label_Control_your_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation.
        /// </summary>
        public static string label_Conversation {
            get {
                return ResourceManager.GetString("label_Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation Notifications.
        /// </summary>
        public static string label_Conversation_Notifications {
            get {
                return ResourceManager.GetString("label_Conversation_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string label_cuont_file {
            get {
                return ResourceManager.GetString("label_cuont_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string label_cuont_images {
            get {
                return ResourceManager.GetString("label_cuont_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string label_cuont_sounds {
            get {
                return ResourceManager.GetString("label_cuont_sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string label_cuont_video {
            get {
                return ResourceManager.GetString("label_cuont_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string label_D {
            get {
                return ResourceManager.GetString("label_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string label_Decline {
            get {
                return ResourceManager.GetString("label_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined your call.
        /// </summary>
        public static string label_Declined_your_call {
            get {
                return ResourceManager.GetString("label_Declined_your_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete conversation.
        /// </summary>
        public static string label_Delete_conversation_ListBoxItem {
            get {
                return ResourceManager.GetString("label_Delete_conversation_ListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string label_Download {
            get {
                return ResourceManager.GetString("label_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emoji Icons.
        /// </summary>
        public static string label_Emoji_Icons {
            get {
                return ResourceManager.GetString("label_Emoji_Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string label_Empty {
            get {
                return ResourceManager.GetString("label_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Video Call.
        /// </summary>
        public static string label_End_Video_Call {
            get {
                return ResourceManager.GetString("label_End_Video_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Api Id is wrong Or Appliction is not verified.
        /// </summary>
        public static string label_Error_Api_Id {
            get {
                return ResourceManager.GetString("label_Error_Api_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error found, please try again later.
        /// </summary>
        public static string label_Error_found {
            get {
                return ResourceManager.GetString("label_Error_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone in this conversation will see this..
        /// </summary>
        public static string label_Everyone_in_this_conversation {
            get {
                return ResourceManager.GetString("label_Everyone_in_this_conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Screen Compress.
        /// </summary>
        public static string label_Full_Screen_Compress {
            get {
                return ResourceManager.GetString("label_Full_Screen_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Screen Expand.
        /// </summary>
        public static string label_Full_Screen_Expand {
            get {
                return ResourceManager.GetString("label_Full_Screen_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get it here.
        /// </summary>
        public static string label_GetAndroidLinkButton {
            get {
                return ResourceManager.GetString("label_GetAndroidLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gift.
        /// </summary>
        public static string Label_gift {
            get {
                return ResourceManager.GetString("Label_gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string label_GoogleButton {
            get {
                return ResourceManager.GetString("label_GoogleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string label_H {
            get {
                return ResourceManager.GetString("label_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image (1080 X 720).
        /// </summary>
        public static string label_Image_size {
            get {
                return ResourceManager.GetString("label_Image_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        public static string label_Incorrect_username_or_password {
            get {
                return ResourceManager.GetString("label_Incorrect_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is calling you.
        /// </summary>
        public static string label_is_calling_you {
            get {
                return ResourceManager.GetString("label_is_calling_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (TCP if available or HTTP).
        /// </summary>
        public static string label_Item_Auto_TCP_HTTP {
            get {
                return ResourceManager.GetString("label_Item_Auto_TCP_HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string label_Item_Files {
            get {
                return ResourceManager.GetString("label_Item_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP With Webclient.
        /// </summary>
        public static string label_Item_HTTP_With_Webclient {
            get {
                return ResourceManager.GetString("label_Item_HTTP_With_Webclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string label_Item_Images {
            get {
                return ResourceManager.GetString("label_Item_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string label_Item_Media {
            get {
                return ResourceManager.GetString("label_Item_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stickers.
        /// </summary>
        public static string label_Item_My_Stickers {
            get {
                return ResourceManager.GetString("label_Item_My_Stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending.
        /// </summary>
        public static string label_Item_Trending {
            get {
                return ResourceManager.GetString("label_Item_Trending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us and start adding your friends and more..
        /// </summary>
        public static string label_Join_us_and_start {
            get {
                return ResourceManager.GetString("label_Join_us_and_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me sign in.
        /// </summary>
        public static string label_Keep_me {
            get {
                return ResourceManager.GetString("label_Keep_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        public static string label_last_seen {
            get {
                return ResourceManager.GetString("label_last_seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string label_LastseenUser {
            get {
                return ResourceManager.GetString("label_LastseenUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent calls.
        /// </summary>
        public static string label_Lbl_No_call {
            get {
                return ResourceManager.GetString("label_Lbl_No_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages.
        /// </summary>
        public static string label_Lbl_No_Chat_Messages {
            get {
                return ResourceManager.GetString("label_Lbl_No_Chat_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Media, Files and Docs.
        /// </summary>
        public static string label_Lbl_No_Media {
            get {
                return ResourceManager.GetString("label_Lbl_No_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any friends to display.
        /// </summary>
        public static string label_Lbl_No_Users_Contact {
            get {
                return ResourceManager.GetString("label_Lbl_No_Users_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or via.
        /// </summary>
        public static string label_Lbl_Orvia {
            get {
                return ResourceManager.GetString("label_Lbl_Orvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your search by typing on the box.
        /// </summary>
        public static string label_Lbl_Search_User {
            get {
                return ResourceManager.GetString("label_Lbl_Search_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Links.
        /// </summary>
        public static string label_Lbl_Social_Links {
            get {
                return ResourceManager.GetString("label_Lbl_Social_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string label_Lnk_About {
            get {
                return ResourceManager.GetString("label_Lnk_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from file.
        /// </summary>
        public static string label_Lnk_Choose_file {
            get {
                return ResourceManager.GetString("label_Lnk_Choose_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string label_Lnk_Clear_all {
            get {
                return ResourceManager.GetString("label_Lnk_Clear_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string label_Lnk_Contact_Us {
            get {
                return ResourceManager.GetString("label_Lnk_Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage local storage.
        /// </summary>
        public static string label_Lnk_Manage_local {
            get {
                return ResourceManager.GetString("label_Lnk_Manage_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manag and reorder sticker packs.
        /// </summary>
        public static string label_Lnk_sticker {
            get {
                return ResourceManager.GetString("label_Lnk_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More Messages.
        /// </summary>
        public static string label_Load_More_Messages {
            get {
                return ResourceManager.GetString("label_Load_More_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string label_Loading {
            get {
                return ResourceManager.GetString("label_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string label_LoadingCancelbutton {
            get {
                return ResourceManager.GetString("label_LoadingCancelbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string label_location {
            get {
                return ResourceManager.GetString("label_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not available.
        /// </summary>
        public static string label_location_not_available {
            get {
                return ResourceManager.GetString("label_location_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using Facebook.
        /// </summary>
        public static string label_Login_using_Facebook {
            get {
                return ResourceManager.GetString("label_Login_using_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using Instagram.
        /// </summary>
        public static string label_Login_using_Instagram {
            get {
                return ResourceManager.GetString("label_Login_using_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using Twitter.
        /// </summary>
        public static string label_Login_using_Twitter {
            get {
                return ResourceManager.GetString("label_Login_using_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using VK.
        /// </summary>
        public static string label_Login_using_VK {
            get {
                return ResourceManager.GetString("label_Login_using_VK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string label_Logout_Button {
            get {
                return ResourceManager.GetString("label_Logout_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for free Video/Audio chat?.
        /// </summary>
        public static string label_Looking_for_free {
            get {
                return ResourceManager.GetString("label_Looking_for_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string label_M {
            get {
                return ResourceManager.GetString("label_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string label_Maximize {
            get {
                return ResourceManager.GetString("label_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media,Links and Files.
        /// </summary>
        public static string label_Media_And_Files {
            get {
                return ResourceManager.GetString("label_Media_And_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Notifications.
        /// </summary>
        public static string label_Message_Notifications {
            get {
                return ResourceManager.GetString("label_Message_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sound.
        /// </summary>
        public static string label_Message_Sound {
            get {
                return ResourceManager.GetString("label_Message_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your Message.
        /// </summary>
        public static string label_MessageBoxText {
            get {
                return ResourceManager.GetString("label_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string label_Min {
            get {
                return ResourceManager.GetString("label_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string label_Minimize {
            get {
                return ResourceManager.GetString("label_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string label_More {
            get {
                return ResourceManager.GetString("label_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More then 300+ Stickers are now available for you..
        /// </summary>
        public static string label_More_then_Stickers {
            get {
                return ResourceManager.GetString("label_More_then_Stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search messages.
        /// </summary>
        public static string label_MSG_searchMessages {
            get {
                return ResourceManager.GetString("label_MSG_searchMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string label_NameTextBox {
            get {
                return ResourceManager.GetString("label_NameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Messages.
        /// </summary>
        public static string label_No_More_Messages {
            get {
                return ResourceManager.GetString("label_No_More_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string label_Notifications {
            get {
                return ResourceManager.GetString("label_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string label_NotificationsControlButton {
            get {
                return ResourceManager.GetString("label_NotificationsControlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now App is available for Android.
        /// </summary>
        public static string label_Now_App_is_available {
            get {
                return ResourceManager.GetString("label_Now_App_is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string label_offline {
            get {
                return ResourceManager.GetString("label_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string label_Online {
            get {
                return ResourceManager.GetString("label_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string label_Open_File {
            get {
                return ResourceManager.GetString("label_Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string label_Options {
            get {
                return ResourceManager.GetString("label_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string label_PasswordBox {
            get {
                return ResourceManager.GetString("label_PasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a color for this conversation.
        /// </summary>
        public static string label_Pick_color {
            get {
                return ResourceManager.GetString("label_Pick_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connction.
        /// </summary>
        public static string label_Please_check_your_internet {
            get {
                return ResourceManager.GetString("label_Please_check_your_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your Confirm password.
        /// </summary>
        public static string label_Please_write_confirm_password {
            get {
                return ResourceManager.GetString("label_Please_write_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your Email.
        /// </summary>
        public static string label_Please_write_your_Email {
            get {
                return ResourceManager.GetString("label_Please_write_your_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your password.
        /// </summary>
        public static string label_Please_write_your_password {
            get {
                return ResourceManager.GetString("label_Please_write_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your username.
        /// </summary>
        public static string label_Please_write_your_username {
            get {
                return ResourceManager.GetString("label_Please_write_your_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        public static string label_Profile_Settings {
            get {
                return ResourceManager.GetString("label_Profile_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there i am using .
        /// </summary>
        public static string label_ProfileUserAbout {
            get {
                return ResourceManager.GetString("label_ProfileUserAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string label_ProfileViewLinkButton {
            get {
                return ResourceManager.GetString("label_ProfileViewLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro Users.
        /// </summary>
        public static string label_proUsers {
            get {
                return ResourceManager.GetString("label_proUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Contacts.
        /// </summary>
        public static string label_Refresh_Contacts {
            get {
                return ResourceManager.GetString("label_Refresh_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign UP!.
        /// </summary>
        public static string label_Registerbutton {
            get {
                return ResourceManager.GetString("label_Registerbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string label_RegisterConfirmPasswordTextBox {
            get {
                return ResourceManager.GetString("label_RegisterConfirmPasswordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string label_RegisterEmailTextBox {
            get {
                return ResourceManager.GetString("label_RegisterEmailTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string label_RegisterPasswordTextBox {
            get {
                return ResourceManager.GetString("label_RegisterPasswordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string label_RegisterUsernameTextBox {
            get {
                return ResourceManager.GetString("label_RegisterUsernameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string label_RightBigText_Login {
            get {
                return ResourceManager.GetString("label_RightBigText_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up!.
        /// </summary>
        public static string label_RightBigText_Signin {
            get {
                return ResourceManager.GetString("label_RightBigText_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your conversation with your family and friends..
        /// </summary>
        public static string label_RightSmallText_Login {
            get {
                return ResourceManager.GetString("label_RightSmallText_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us and start adding your friends and more..
        /// </summary>
        public static string label_RightSmallText_Signin {
            get {
                return ResourceManager.GetString("label_RightSmallText_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Conversation.
        /// </summary>
        public static string label_SearchMesageButton {
            get {
                return ResourceManager.GetString("label_SearchMesageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string label_SearchMsgButton {
            get {
                return ResourceManager.GetString("label_SearchMsgButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec.
        /// </summary>
        public static string label_Sec {
            get {
                return ResourceManager.GetString("label_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string label_Sel_Gender {
            get {
                return ResourceManager.GetString("label_Sel_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string label_Sel_language {
            get {
                return ResourceManager.GetString("label_Sel_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string label_Send {
            get {
                return ResourceManager.GetString("label_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send you an audio file.
        /// </summary>
        public static string label_Send_you_an_audio_file {
            get {
                return ResourceManager.GetString("label_Send_you_an_audio_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send you an file.
        /// </summary>
        public static string label_Send_you_an_file {
            get {
                return ResourceManager.GetString("label_Send_you_an_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send you an gif image.
        /// </summary>
        public static string label_Send_you_an_gif_image {
            get {
                return ResourceManager.GetString("label_Send_you_an_gif_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send you an image file.
        /// </summary>
        public static string label_Send_you_an_image_file {
            get {
                return ResourceManager.GetString("label_Send_you_an_image_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send you an sticker file.
        /// </summary>
        public static string label_Send_you_an_sticker_file {
            get {
                return ResourceManager.GetString("label_Send_you_an_sticker_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send you an video file.
        /// </summary>
        public static string label_Send_you_an_video_file {
            get {
                return ResourceManager.GetString("label_Send_you_an_video_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string label_Settings {
            get {
                return ResourceManager.GetString("label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string label_Settings_Advanced {
            get {
                return ResourceManager.GetString("label_Settings_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Settings.
        /// </summary>
        public static string label_Settings_Chat {
            get {
                return ResourceManager.GetString("label_Settings_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string label_Settings_General {
            get {
                return ResourceManager.GetString("label_Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string label_Settings_Notifications {
            get {
                return ResourceManager.GetString("label_Settings_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share files with.
        /// </summary>
        public static string label_Share_files {
            get {
                return ResourceManager.GetString("label_Share_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up!.
        /// </summary>
        public static string label_Sign_Up {
            get {
                return ResourceManager.GetString("label_Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay in Sync across your devices.
        /// </summary>
        public static string label_Stay_in_Sync {
            get {
                return ResourceManager.GetString("label_Stay_in_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync your chats from device to device and keep the conversation going.
        /// </summary>
        public static string label_Sync_your_chats {
            get {
                return ResourceManager.GetString("label_Sync_your_chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait...
        /// </summary>
        public static string label_TextBlockMessege {
            get {
                return ResourceManager.GetString("label_TextBlockMessege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whats new on this version ?.
        /// </summary>
        public static string label_this_version {
            get {
                return ResourceManager.GetString("label_this_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size.
        /// </summary>
        public static string label_total_size {
            get {
                return ResourceManager.GetString("label_total_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending HashTags.
        /// </summary>
        public static string label_Trending_HashTags {
            get {
                return ResourceManager.GetString("label_Trending_HashTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there i am using .
        /// </summary>
        public static string label_Txt_About_me {
            get {
                return ResourceManager.GetString("label_Txt_About_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string label_Txt_Address {
            get {
                return ResourceManager.GetString("label_Txt_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string label_Txt_Back {
            get {
                return ResourceManager.GetString("label_Txt_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Date.
        /// </summary>
        public static string label_Txt_Birthday {
            get {
                return ResourceManager.GetString("label_Txt_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string label_Txt_Email {
            get {
                return ResourceManager.GetString("label_Txt_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string label_Txt_Facebook {
            get {
                return ResourceManager.GetString("label_Txt_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string label_Txt_Google {
            get {
                return ResourceManager.GetString("label_Txt_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string label_Txt_Instagram {
            get {
                return ResourceManager.GetString("label_Txt_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin.
        /// </summary>
        public static string label_Txt_Linkedin {
            get {
                return ResourceManager.GetString("label_Txt_Linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local strong.
        /// </summary>
        public static string label_txt_Local_strong {
            get {
                return ResourceManager.GetString("label_txt_Local_strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Conversations yet..
        /// </summary>
        public static string label_Txt_No_Conversations {
            get {
                return ResourceManager.GetString("label_Txt_No_Conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string label_Txt_Phone_number {
            get {
                return ResourceManager.GetString("label_Txt_Phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a recipient to start the chat.
        /// </summary>
        public static string label_Txt_Please_select {
            get {
                return ResourceManager.GetString("label_Txt_Please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string label_Txt_School {
            get {
                return ResourceManager.GetString("label_Txt_School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Users.
        /// </summary>
        public static string label_Txt_Search_BoxContact {
            get {
                return ResourceManager.GetString("label_Txt_Search_BoxContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Users.
        /// </summary>
        public static string label_Txt_SearchBoxOnline {
            get {
                return ResourceManager.GetString("label_Txt_SearchBoxOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Gifs.
        /// </summary>
        public static string label_Txt_searchGifs {
            get {
                return ResourceManager.GetString("label_Txt_searchGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Users.
        /// </summary>
        public static string label_Txt_searchMessages {
            get {
                return ResourceManager.GetString("label_Txt_searchMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string label_Txt_Twitter {
            get {
                return ResourceManager.GetString("label_Txt_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string label_Txt_Username {
            get {
                return ResourceManager.GetString("label_Txt_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VKontakte.
        /// </summary>
        public static string label_Txt_Vk {
            get {
                return ResourceManager.GetString("label_Txt_Vk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string label_Txt_Website {
            get {
                return ResourceManager.GetString("label_Txt_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubePlay.
        /// </summary>
        public static string label_Txt_Youtube {
            get {
                return ResourceManager.GetString("label_Txt_Youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typping....
        /// </summary>
        public static string label_Typping {
            get {
                return ResourceManager.GetString("label_Typping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Friends.
        /// </summary>
        public static string label_User_Friends {
            get {
                return ResourceManager.GetString("label_User_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username doesn&apos;t exists.
        /// </summary>
        public static string label_Username_does_not_exists {
            get {
                return ResourceManager.GetString("label_Username_does_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video call.
        /// </summary>
        public static string label_Video_call {
            get {
                return ResourceManager.GetString("label_Video_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string label_View_Profile_ListBoxItem {
            get {
                return ResourceManager.GetString("label_View_Profile_ListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will connect to your account and get all your data.
        /// </summary>
        public static string label_We_will_connect {
            get {
                return ResourceManager.GetString("label_We_will_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wherever you are. Keep in touch with friends Across Android, iOS and the web.
        /// </summary>
        public static string label_Wherever_you_are {
            get {
                return ResourceManager.GetString("label_Wherever_you_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Mode :.
        /// </summary>
        public static string label2_Night_Mode {
            get {
                return ResourceManager.GetString("label2_Night_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        public static string Label2_No_file_selected {
            get {
                return ResourceManager.GetString("Label2_No_file_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search result found.
        /// </summary>
        public static string Label2_No_search_result_found {
            get {
                return ResourceManager.GetString("Label2_No_search_result_found", resourceCulture);
            }
        }
    }
}
